INSERT INTO wine_moods (wine_id, mood) VALUES

(21, 'INTELLECTUAL_TASTING'),
(21, 'RELAX'),

(22, 'ROMANTIC'),
(22, 'RELAX'),

(23, 'CELEBRATION'),
(23, 'ENERGETIC'),

(24, 'INTELLECTUAL_TASTING'),
(24, 'CELEBRATION'),

(25, 'INTELLECTUAL_TASTING'),
(25, 'RELAX'),

(26, 'ROMANTIC'),
(26, 'RELAX'),

(27, 'CELEBRATION'),
(27, 'ENERGETIC'),

(28, 'INTELLECTUAL_TASTING'),
(28, 'RELAX'),

(29, 'INTELLECTUAL_TASTING'),
(29, 'RELAX'),

(30, 'ROMANTIC'),
(30, 'RELAX'),

(31, 'CELEBRATION'),
(31, 'ENERGETIC'),

(32, 'RELAX'),
(32, 'INTELLECTUAL_TASTING'),

(33, 'ROMANTIC'),
(33, 'RELAX'),

(34, 'INTELLECTUAL_TASTING'),
(34, 'CELEBRATION'),

(35, 'RELAX'),
(35, 'ENERGETIC'),

(36, 'CELEBRATION'),
(36, 'ROMANTIC'),

(37, 'INTELLECTUAL_TASTING'),
(37, 'RELAX'),

(38, 'INTELLECTUAL_TASTING'),
(38, 'RELAX'),

(39, 'ROMANTIC'),
(39, 'RELAX'),

(40, 'CELEBRATION'),
(40, 'RELAX');