CREATE TABLE foods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_image_url VARCHAR(1000),
    food_category VARCHAR(50) NOT NULL,
    food_type VARCHAR(50) NOT NULL
);

CREATE TABLE wine_food_pairing (
    wine_id BIGINT NOT NULL,
    food_id BIGINT NOT NULL,

    CONSTRAINT fk_wine_food
        FOREIGN KEY (wine_id) REFERENCES wines(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_food_wine
        FOREIGN KEY (food_id) REFERENCES foods(id)
        ON DELETE CASCADE,

    CONSTRAINT pk_wine_food_pairing PRIMARY KEY (wine_id, food_id)
);

CREATE INDEX idx_wine_food_pairing_wine_id
    ON wine_food_pairing(wine_id);

CREATE INDEX idx_wine_food_pairing_food_id
    ON wine_food_pairing(food_id);