INSERT INTO moods (name) VALUES ('ROMANTIC');
INSERT INTO moods (name) VALUES ('RELAX');
INSERT INTO moods (name) VALUES ('CELEBRATION');
INSERT INTO moods (name) VALUES ('ENERGETIC');
INSERT INTO moods (name) VALUES ('INTELLECTUAL_TASTING');